#
# Module manifest for module 'ReverseDSC'
#
# Generated by: Team Microsoft365DSC
#
# Generated on: 2026/08/07
#
@{
    ModuleVersion     = '2.0.0.36'
    GUID              = '6c1176a0-4fac-4134-8ca2-3fa8a21a7b90'
    Author            = 'Microsoft Corporation'
    CompanyName       = 'Microsoft Corporation'
    Copyright         = '(c) 2015-2026 Microsoft Corporation. All rights reserved.'
    Description       = 'This DSC module is used to extract the DSC Configuration of existing environments.'
    PowerShellVersion = '5.1'
    NestedModules     = @("ReverseDSC.Core.psm1")
    CmdletsToExport   = @()
    FunctionsToExport = @(
        "Clear-ConfigurationDataContent",
        "Clear-ReverseDSCUserNames",
        "Get-DSCParamType",
        "Get-DSCBlock",
        "Get-DSCFakeParameters",
        "Get-DSCDependsOnBlock",
        "Get-Credentials",
        "Resolve-Credentials",
        "Save-Credentials",
        "Test-Credentials",
        "Convert-DSCStringParamToVariable",
        "Get-ConfigurationDataContent",
        "New-ConfigurationDataDocument",
        "Add-ConfigurationDataEntry",
        "Get-ConfigurationDataEntry",
        "Add-ReverseDSCUserName"
    )
    AliasesToExport   = @()
    PrivateData       = @{
        PSData = @{

            Tags         = @('DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource', 'ReverseDSC')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/Microsoft365DSC/ReverseDSC/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/Microsoft365DSC/ReverseDSC'

            # A URL to an icon representing this module.
            IconUri      = 'https://github.com/Microsoft365DSC/ReverseDSC/blob/master/Images/DSCModuleIcon.png?raw=true'

            ReleaseNotes = '* Fixed PSCredential values being emitted as their type name instead of the $Creds variable.
* Fixed Convert-DSCStringParamToVariable throwing when a value has no closing quote.
* Fixed empty comment lines in the generated ConfigurationData document.
* CIM instances and arrays of CIM instances are now rendered as MOF style blocks instead of their class name.
* Get-ConfigurationDataEntry now searches all nodes when no node is specified, as documented.
* Removed unreachable code paths.'

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
