#
# Module manifest for module 'ReverseDSC'
#
# Generated by: Team Microsoft365DSC
#
# Generated on: 2026/08/25
#
@{
    RootModule             = 'ReverseDSC.dll'
    ModuleVersion          = '3.0.0.0'
    GUID                   = '6c1176a0-4fac-4134-8ca2-3fa8a21a7b90'
    Author                 = 'Microsoft Corporation'
    CompanyName            = 'Microsoft Corporation'
    Copyright              = '(c) 2015-2026 Microsoft Corporation. All rights reserved.'
    Description            = 'This DSC module is used to extract the DSC Configuration of existing environments.'
    PowerShellVersion      = '5.1'
    CompatiblePSEditions   = @('Desktop', 'Core')
    DotNetFrameworkVersion = '4.7.2'
    CLRVersion             = '4.0'
    FunctionsToExport      = @()
    CmdletsToExport        = @(
        "Clear-ConfigurationDataContent",
        "Clear-ReverseDSCUserNames",
        "Get-DSCParamType",
        "Get-DSCBlock",
        "Get-DSCFakeParameters",
        "Get-DSCDependsOnBlock",
        "Get-Credentials",
        "Resolve-Credentials",
        "Save-Credentials",
        "Test-Credentials",
        "Convert-DSCStringParamToVariable",
        "Get-ConfigurationDataContent",
        "New-ConfigurationDataDocument",
        "Add-ConfigurationDataEntry",
        "Get-ConfigurationDataEntry",
        "Add-ReverseDSCUserName"
    )
    VariablesToExport      = @()
    AliasesToExport        = @()
    PrivateData            = @{
        PSData = @{

            Tags         = @('DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource', 'ReverseDSC')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/Microsoft365DSC/ReverseDSC/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/Microsoft365DSC/ReverseDSC'

            # A URL to an icon representing this module.
            IconUri      = 'https://github.com/Microsoft365DSC/ReverseDSC/blob/master/Images/DSCModuleIcon.png?raw=true'

            ReleaseNotes = '* Rewrote the module as a compiled binary module targeting netstandard2.0.
* New-ConfigurationDataDocument now always writes UTF-8 without a byte order mark.'

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
